baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-redirect'

[module]
  # Build and serve using local mod-redirect clone declared in the named Hugo workspace:
  workspace = "mod-redirect.work"
  [[module.imports]]
    path = "github.com/anoduck/mod-redirect"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"